services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    volumes:
      - "./data:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: Europe/Oslo
    restart: unless-stopped
    stop_grace_period: 60s

